### ISSUE TITLE
Service level directives 'user', 'command', 'entrypoint' are ignored

### ISSUE THREAD

**Issue by deromka** [ansible/ansible-container#351] opened 2017-01-08 09:17 UTC
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "2"
defaults:
  docker_registry_name: zzz
  docker_repo_staging: aaa
  docker_repo_releases: bbb
  profile: general
  profile_version: 1111
  entrypoint: /bin/sh
  base_image: MMM
  container_user: kkkuser
  working_dir: /scripts

services:
  # Add your containers here, specifying the base image you want to build from

  # profile data volume container is a pre-requisite
  profile:
    image: "{{ docker_registry_name }}/{{ docker_repo_staging }}/{{ profile }}_profile:{{ profile_version }}"


  {{ service_name }}:
    image: {{ base_image }}
    command: {{ entrypoint }}
    entrypoint: {{ entrypoint }}
    user: {{ container_user }}
    working_dir: {{ working_dir }}
    ports: {{ ports }}
    volumes_from:
    - profile
    dev_overrides:
      environment:
        - "DEBUG=1"
```

##### main.yml 

```
---
- hosts: profile
  gather_facts: false

- hosts: "{{ lookup('env','service_name') }}"
  gather_facts: false
  vars:
    service_name: "{{ lookup('env','service_name') }}"
  vars_files:
    - "/ansible-container/services/{{ service_name }}/vars.yml"
  roles:
    - role: install-service
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0
Darwin, RDEMBITS-M-R0Q4, 16.3.0, Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64, x86_64
2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] /usr/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 20,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 20,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'276'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'ICQP:ZKPS:L2VK:O2DE:QHGY:VD7O:IVE2:JKWC:P3A5:MZWJ:P7XK:3XDU',
 u'IPv4Forwarding': True,
 u'Images': 303,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': False,
 u'KernelVersion': u'4.4.39-moby',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 2094940160,
 u'MemoryLimit': True,
 u'NCPU': 2,
 u'NEventsListener': 1,
 u'NFd': 17,
 u'NGoroutines': 29,
 u'Name': u'moby',
 u'NoProxy': u'*.local, 169.254/16',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Alpine Linux v3.4',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'overlay', u'bridge', u'host', u'null'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.5',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2017-01-08T09:06:26.662256063Z'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-12-16T06:14:34.536244887+00:00',
 u'GitCommit': u'7392c3b',
 u'GoVersion': u'go1.6.4',
 u'KernelVersion': u'4.4.39-moby',
 u'Os': u'linux',
 u'Version': u'1.12.5'}
```
##### SUMMARY

The following service level directives are ignored and does not use the inserted values:

user
entrypoint
command 

##### STEPS TO REPRODUCE

container.yml contains 'user', 'entrypoint', 'command' directives with values, but the ansible container output during build shows them with their default values

```
Rendered Jinja Template:
ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  privileged: true
  image: "ansible/ansible-container-builder:0.2"
  command: "/usr/local/bin/builder.sh /usr/bin/ansible-playbook -vvv -i /etc/ansible/ansible-container-inventory.py -c docker -vvvvv main.yml"
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
    - ANSIBLE_ORCHESTRATED_HOSTS=profile,sgw
    - ANSIBLE_CONTAINER=1
    
    
    - service_name=sgw
    
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
    - /docker:/ansible-container/:Z
    
    
  working_dir: /ansible-container/ansible/
profile:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  environment: {ANSIBLE_CONTAINER: 1}
  image: docker-staging/general_profile:11.9.4_ca04a51
  user: root
  working_dir: /
sgw:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  environment: {ANSIBLE_CONTAINER: 1}
  image: docker/openjdk
  ports: ['33222:33222']
  user: root
  volumes_from: [profile]
  working_dir: /

```

##### EXPECTED RESULTS

expected user,entrypoint,command directives will use the set values

##### ACTUAL RESULTS

user,entrypoint,command directives ignore the set values

```
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Project name is docker
Using temporary directory /var/folders/kt/5dy3ghgd55n2_sd_8rnw7hqr0000gp/T/tmpOx1Z2d...
Cleaning up temporary directory /var/folders/kt/5dy3ghgd55n2_sd_8rnw7hqr0000gp/T/tmpOx1Z2d...
Default vars:
{
    "base_image": "dockerhub.AAA.com/vge-docker/openjdk",
    "container_user": "ndsuser",
    "docker_registry_name": "dockerhub.AAA.com",
    "docker_repo_releases": "vge-docker-releases",
    "docker_repo_staging": "vge-docker-staging",
    "entrypoint": "/bin/sh",
    "profile": "general",
    "profile_version": "11.9.4_ca04a51",
    "working_dir": "/scripts"
}
Reading variables from var file...
Use variable file: /Users/JJJ/devel/automation/drm-he-ci/docker/services/sgw/vars.yml
Getting environment variables...
Template variables:
 {
    "base_image": "dockerhub.AAA.com/vge-docker/openjdk",
    "code_to_execute_after_mount": "python /scripts/evaluate-template-file.py '/opt/nds/sgw/etc/ccoDef.xml.j2' '/opt/nds/sgw/etc/ccoDef.xml'",
    "component_profile_name": "sgw",
    "container_user": "ndsuser",
    "debug": 1,
    "docker_registry_name": "dockerhub.AAA.com",
    "docker_repo_releases": "vge-docker-releases",
    "docker_repo_staging": "vge-docker-staging",
    "entrypoint": "/bin/sh",
    "image_name": "sgw",
    "log_path": "/opt/nds/sgw/log/sgw.log",
    "mvn_artifact_id": "secure-gateway",
    "mvn_classifier": "rh6",
    "mvn_group_id": "com.nds.ch.sgw",
    "ports": [
        "33222:33222"
    ],
    "profile": "general",
    "profile_version": "11.9.4_ca04a51",
    "service_name": "sgw",
    "version": "2.26.1-0",
    "working_dir": "/scripts"
}
Config:
{
    "registries": {
        "vge-docker-releases": {
            "url": "dockerhub.AAA.com/vge-docker-releases"
        },
        "vge-docker-staging": {
            "namespace": "",
            "url": "dockerhub.AAA.com/vge-docker-staging"
        }
    },
    "services": {
        "profile": {
            "image": "dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51"
        },
        "sgw": {
            "command": "/bin/sh",
            "image": "dockerhub.AAA.com/vge-docker/openjdk",
            "ports": [
                "33222:33222"
            ],
            "user": "ndsuser",
            "volumes_from": [
                "profile"
            ],
            "working_dir": "/scripts"
        }
    },
    "version": "2"
}
Initialized with params: {'with_volumes': [], 'local_builder': False, 'service': None, 'with_variables': ['service_name=sgw'], 'rebuild': False, 'subcommand': 'build', 'var_file': 'services/sgw/vars.yml', 'engine_args': {'local_builder': False, 'subcommand': 'build', 'base_path': '/Users/JJJ/devel/automation/drm-he-ci/docker', 'ansible_options': ['-vvvvv'], 'flatten': False, 'no_purge_last': True, 'with_volumes': [], 'service': None, 'engine_name': 'docker', 'with_variables': ['service_name=sgw'], 'rebuild': False, 'var_file': 'services/sgw/vars.yml', 'engine_args': {...}, 'save_build_container': False, 'roles_path': None, 'kwargs': {'with_volumes': [], 'with_variables': ['service_name=sgw'], 'subcommand': 'build', 'var_file': 'services/sgw/vars.yml', 'debug': True, 'no_purge_last': True}, 'debug': True, 'purge_last': True}, 'save_build_container': False, 'purge_last': True, 'roles_path': None, 'ansible_options': ['-vvvvv'], 'flatten': False, 'kwargs': {'with_volumes': [], 'with_variables': ['service_name=sgw'], 'subcommand': 'build', 'var_file': 'services/sgw/vars.yml', 'debug': True, 'no_purge_last': True}, 'debug': True, 'no_purge_last': True}
Using temporary directory /var/folders/kt/5dy3ghgd55n2_sd_8rnw7hqr0000gp/T/tmpiJfhYX...
Starting Docker Compose engine to build your images...
Using temporary directory /var/folders/kt/5dy3ghgd55n2_sd_8rnw7hqr0000gp/T/tmpzO2nCu...
Compose derived from config:
{'profile': {'image': 'dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51'}, 'sgw': {'image': 'dockerhub.AAA.com/vge-docker/openjdk', 'working_dir': '/scripts', 'command': '/bin/sh', 'user': 'ndsuser', 'volumes_from': ['profile'], 'ports': ['33222:33222']}}
{'profile': {'command': 'sh -c "while true; do sleep 1; done"', 'image': 'dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51', 'entrypoint': [], 'working_dir': '/', 'user': 'root'}, 'sgw': {'image': 'dockerhub.AAA.com/vge-docker/openjdk', 'working_dir': '/', 'command': 'sh -c "while true; do sleep 1; done"', 'user': 'root', 'volumes_from': ['profile'], 'entrypoint': [], 'ports': ['33222:33222']}}
Config YAML is
profile:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51
  user: root
  working_dir: /
sgw:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: dockerhub.AAA.com/vge-docker/openjdk
  ports: ['33222:33222']
  user: root
  volumes_from: [profile]
  working_dir: /

Rendered Jinja Template:
ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  privileged: true
  image: "ansible/ansible-container-builder:0.2"
  command: /usr/local/bin/builder.sh /usr/bin/ansible-playbook -i /etc/ansible/ansible-container-inventory.py -c docker -vvvvv --list-hosts main.yml
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
    - ANSIBLE_ORCHESTRATED_HOSTS=profile,sgw
    - ANSIBLE_CONTAINER=1
    
    
    - service_name=sgw
    
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
    - /Users/JJJ/devel/automation/drm-he-ci/docker:/ansible-container/:Z
    
    
  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
profile:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51
  user: root
  working_dir: /
sgw:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: dockerhub.AAA.com/vge-docker/openjdk
  ports: ['33222:33222']
  user: root
  volumes_from: [profile]
  working_dir: /

Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
--list-hosts
ansible-container_1  | Host profile failed
ansible-container_1  | Host sgw failed
ansible-container_1  | Using /ansible-container/ansible/ansible.cfg as config file
ansible-container_1  | 2 plays in main.yml
ansible-container_1  | 
ansible-container_1  | playbook: main.yml
ansible-container_1  | 
ansible-container_1  |   play #1 (profile): profile     TAGS: []
ansible-container_1  |     pattern: [u'profile']
ansible-container_1  |     hosts (1):
ansible-container_1  |       profile
ansible-container_1  | 
ansible-container_1  |   play #2 (sgw): sgw     TAGS: []
ansible-container_1  |     pattern: [u'sgw']
ansible-container_1  |     hosts (1):
ansible-container_1  |       sgw
ansible_ansible-container_1 exited with code 0

Cleaning up temporary directory /var/folders/kt/5dy3ghgd55n2_sd_8rnw7hqr0000gp/T/tmpzO2nCu...
Compose derived from config:
{'profile': {'image': 'dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51'}, 'sgw': {'image': 'dockerhub.AAA.com/vge-docker/openjdk', 'working_dir': '/scripts', 'command': '/bin/sh', 'user': 'ndsuser', 'volumes_from': ['profile'], 'ports': ['33222:33222']}}
Orchestrated hosts: ['profile', 'sgw']
Setting profile to sleep
No image found for tag docker-profile:latest, so building from scratch
Setting sgw to sleep
No image found for tag docker-sgw:latest, so building from scratch
{'profile': {'image': 'dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51', 'environment': {'ANSIBLE_CONTAINER': 1}, 'working_dir': '/', 'command': 'sh -c "while true; do sleep 1; done"', 'user': 'root', 'entrypoint': []}, 'sgw': {'image': 'dockerhub.AAA.com/vge-docker/openjdk', 'environment': {'ANSIBLE_CONTAINER': 1}, 'working_dir': '/', 'command': 'sh -c "while true; do sleep 1; done"', 'user': 'root', 'volumes_from': ['profile'], 'entrypoint': [], 'ports': ['33222:33222']}}
Config YAML is
profile:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  environment: {ANSIBLE_CONTAINER: 1}
  image: dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51
  user: root
  working_dir: /
sgw:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  environment: {ANSIBLE_CONTAINER: 1}
  image: dockerhub.AAA.com/vge-docker/openjdk
  ports: ['33222:33222']
  user: root
  volumes_from: [profile]
  working_dir: /

Rendered Jinja Template:
ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  privileged: true
  image: "ansible/ansible-container-builder:0.2"
  command: "/usr/local/bin/builder.sh /usr/bin/ansible-playbook -vvv -i /etc/ansible/ansible-container-inventory.py -c docker -vvvvv main.yml"
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
    - ANSIBLE_ORCHESTRATED_HOSTS=profile,sgw
    - ANSIBLE_CONTAINER=1
    
    
    - service_name=sgw
    
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
    - /Users/JJJ/devel/automation/drm-he-ci/docker:/ansible-container/:Z
    
    
  working_dir: /ansible-container/ansible/
profile:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  environment: {ANSIBLE_CONTAINER: 1}
  image: dockerhub.AAA.com/vge-docker-staging/general_profile:11.9.4_ca04a51
  user: root
  working_dir: /
sgw:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  environment: {ANSIBLE_CONTAINER: 1}
  image: dockerhub.AAA.com/vge-docker/openjdk
  ports: ['33222:33222']
  user: root
  volumes_from: [profile]
  working_dir: /

Attaching to ansible_ansible-container_1, ansible_profile_1, ansible_sgw_1
ansible-container_1  | Host profile running
ansible-container_1  | Host sgw running
ansible-container_1  | Using /ansible-container/ansible/ansible.cfg as config file
ansible-container_1  | Loaded callback default of type stdout, v2.0
ansible-container_1  | 
ansible-container_1  | PLAYBOOK: main.yml *************************************************************
ansible-container_1  | 2 plays in main.yml
ansible-container_1  | 
ansible-container_1  | PLAY [profile] *****************************************************************
ansible-container_1  | 
ansible-container_1  | PLAY [sgw] *********************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [install-service : install epel repo] *************************************
ansible-container_1  | task path: /ansible-container/ansible/roles/install-service/tasks/main.yml:4
ansible-container_1  | <ansible_sgw_1> ESTABLISH DOCKER CONNECTION FOR USER: root
ansible-container_1  | <ansible_sgw_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_sgw_1', u'/bin/sh', '-c', u'/bin/sh -c \'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1483866739.98-197242339256868 `" && echo ansible-tmp-1483866739.98-197242339256868="` echo $HOME/.ansible/tmp/ansible-tmp-1483866739.98-197242339256868 `" ) && sleep 0\'']
ansible-container_1  | <ansible_sgw_1> PUT /tmp/tmpLo8MME TO /root/.ansible/tmp/ansible-tmp-1483866739.98-197242339256868/yum
ansible-container_1  | <ansible_sgw_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_sgw_1', u'/bin/sh', '-c', u'/bin/sh -c \'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1483866739.98-197242339256868/yum; rm -rf "/root/.ansible/tmp/ansible-tmp-1483866739.98-197242339256868/" > /dev/null 2>&1 && sleep 0\'']

```

**Comment by chouseknecht** [comment] 2017-01-09 13:35
Overriding the command, user, and entrypoint directives during the `build` process is intentional. We need to put each service container into a known state before executing the playbook, and mostly we need to know that the container will stay running long enough for the playbook to complete. We also need to connect to the container with a user that actually exists, and of course the *root* user always exists. 

None of this helps your use case, but hopefully it explains the thinking. For what you're attempting to do, I think you can override these things in your playbook. For example, for a given play or task you can set *remote_user*, or use *become*. If you need a process running on the container, you can start it as a background process using either the *command* or *shell* module, and later in the playbook kill it, again using *command* or *shell*. Entrypoint can be handled the same way, by executing a given script or command using the *command* or *shell* modules.

**Comment by chouseknecht** [comment] 2017-01-09 19:39
Labeling as a bug, because it was filed as a bug. But it's really not a bug.

**Comment by brucellino** [comment] 2017-01-10 13:48
Hi @chouseknecht I have a similar issue to this. I want to avoid opening a new issue because I think the same behaviour is at the source of my issue. I am using a mysql image from Docker, which specifies it's own entrypoint to get the db service running. I need to work on that db, by interacting with it using the ansible `mysql_db` module. However, the entrypoint is not executed (only the ansible-container  entrypoint  `command: sh -c "while true; do sleep 1; done"`, so my playbook fails since it can't connect to the db.

**Comment by brucellino** [comment] 2017-01-10 14:56
FWIW, I've found that the image directives (entrypoint, command) are only overridden if Ansible-Container thinks it needs to act on the container. If A-C thinks it's "done" with the container, the image's entrypoint is executed.

**Comment by chouseknecht** [comment] 2017-01-10 15:34
@brucellino, that is correct. It only overrides entrypoint and command when the service is returned by `ansible-playbook --list-hosts main.yml`. So, if `main.yml` is not intended to act on `mysql_db`, then perhaps perform migrations (or other database modifications) from another service container.

Also, know that in the future Ansible Container will stop performing `orchestrated builds`, meaning that it will not bring up all containers, and then perform the build. Instead, it will build each container individually. In other words, start service_a, run `main.yml`, shutdown service_a, start service_b, run `main.yml, stop service_b, and so forth.

For this reason, the better thing to do would be to move the migrations into a script that's part of the entrypoint of a service other than `mysql_db`.

**Comment by chouseknecht** [comment] 2017-01-11 21:57
Closing for now. We can revisit after the new build cache bits land, which maybe, possibly, might by early next week.

**Closed by chouseknecht** 2017-01-11 21:57 UTC
Labels: bug
