### ISSUE TITLE
Ugly error when docker.sock is not there

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-container#755] opened 2017-10-05 07:52 UTC
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
# whatever you want
```

##### OS / ENVIRONMENT
```
# ansible-container --debug version
Ansible Container, version 0.9.2
Linux, 94d26d51335e, 4.4.0-96-generic, #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] /usr/bin/python
```
##### SUMMARY
Ugly error when docker (socket) is not present

##### STEPS TO REPRODUCE
1. setup ansible-container in an environment (docker, vm, ....) WITHOUT docker
2. make a basic setup with container.yml/roles etc.
3. `ansible-container build`

##### EXPECTED RESULTS
Easy message like docker.sock not available, did you install docker ?

##### ACTUAL RESULTS
```
ERROR   Unknown exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 158, in hostcmd_build
    conductor_container_id = engine_obj.get_container_id_for_service('conductor')
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 527, in get_container_id_for_service
    container_info = self.client.containers.get(self.container_name_for_service(service_name))
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 164, in client
    self._client = docker.from_env(version='auto', timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 80, in from_env
    **kwargs_from_env(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 37, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 147, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 174, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by chouseknecht** [comment] 2017-10-05 13:51
@hans-d 

Thanks for reporting this. I think you're right. We could use some better error handling here, if possible.

**Comment by gerl1ng** [comment] 2017-10-24 21:07
Duplicate of #710

**Closed as completed** 2017-10-27 14:08 UTC
Labels: bug, help wanted
