### ISSUE TITLE
Strange effects happened to "Cmd" in container and container image.

### ISSUE THREAD

**Issue by struongpax** [ansible/ansible-container#163] opened 2016-08-10 22:25 UTC
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "1"
services:
    labs:
        image: nginx-nginx:latest 
        ports:
            - "80:80"
        command: ["/root/start.sh"]

registries: {}
```
##### main.yml 
```---
- hosts: all 
  gather_facts: false
  tasks:
    - name: put the nginx file into /etc/nginx/sites-enabled
      copy: src=files/ui3.conf dest=/etc/nginx/sites-enabled/ui3.conf owner=root group=root mode=0644

    - name: update start.sh
      copy: src=files/start.sh dest=/root/start.sh owner=root group=root mode=0755

```
##### OS / ENVIRONMENT

```
ansible-container --debug version
Ansible Container, version 0.1.0
Linux, mintlinux, 4.4.0-31-generic, #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016, x86_64
2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] /usr/bin/python
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 16,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 16,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': False,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/home/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/home/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'150'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'J7F5:QCGL:B3CG:VUIA:BYLS:4UJQ:G77G:QBVZ:ASHL:5O4C:ZAAI:FQB4',
 u'IPv4Forwarding': True,
 u'Images': 149,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.4.0-31-generic',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 16353939456,
 u'MemoryLimit': True,
 u'NCPU': 4,
 u'NEventsListener': 0,
 u'NFd': 25,
 u'NGoroutines': 42,
 u'Name': u'mintlinux',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Ubuntu 16.04 LTS',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'overlay', u'bridge', u'null', u'host'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'apparmor', u'seccomp'],
 u'ServerVersion': u'1.12.0',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-08-10T15:10:54.768392656-07:00'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-07-28T22:11:10.070091404+00:00',
 u'GitCommit': u'8eab29e',
 u'GoVersion': u'go1.6.3',
 u'KernelVersion': u'4.4.0-31-generic',
 u'Os': u'linux',
 u'Version': u'1.12.0'}

```
##### SUMMARY
Using the container image from "ansible-containter build"  with this command: docker run -d labs-labs:latest, my /root/start.sh did not get to run.  When I inspected the container, I found this:

 "Cmd": [
                "sh",
                "-c",
                "while true; do sleep 1; done"
            ],
And inspecting the container image, I found the same "Cmd".

And when I used "ansible-container run", I got this:
labs ansible-container run
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Attaching to ansible_labs_1
labs_1               | Already up-to-date.
labs_1               | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
labs_1               | nginx: configuration file /etc/nginx/nginx.conf test is successful
ansible_labs_1 exited with code 0

but then when I inspected the stopped container I found this: 
],
            "Cmd": [
                "/root/start.sh"
            ],

----
I really do not understand why command was specified in container.yml and the container image did have this set correctly.  What are the logics that when using "ansible-container run" then the container got the right "Cmd" set. 

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment] 2016-08-11 14:08
Seeing if I can reproduce this...

**Comment by j00bar** [comment] 2016-08-11 14:22
This is a duplicate of #116

**Comment by chouseknecht** [comment] 2016-08-11 14:57
Ah. Hadn't gotten that far into looking at this. I see [in the code](https://github.com/ansible/ansible-container/blob/develop/container/docker/engine.py#L514) where we add the CMD, USER and WORDIR values to the image on post build. So in theory the image should have received the *command* specified in container.yml as the CMD value. 

I'm also noticing that @struongpax is running Docker 1.12.0. Wondering if this is a 1.12.0 specific thing. I have not upgraded and tested 1.12.0 at all.

**Comment by chouseknecht** [comment] 2016-08-11 22:40
On 1.11.2 it seems to work OK. After `ansible-container build` the Config.Cmd has the correct Cmd value:

```
$ docker inspect --format="{{ .Config.Cmd }}" test-labs:latest
[/bin/sh -c ['/root/start.sh']]
```

ContainerConfig.Cmd has the value of the command running when the image was built:

```
$ docker inspect --format="{{ .ContainerConfig.Cmd }}" test-labs:latest
[sh -c while true; do sleep 1; done]
```

When I run the container, it tries to run /root/start.sh:

```
$ docker run test-labs:latest
/bin/sh: 1: [/root/start.sh]: not found
```

**Comment by chouseknecht** [comment] 2016-08-11 23:09
Same result on 1.12.0:

```
$ docker inspect --format="{{ .Config.Cmd }}" test-labs:latest
[/bin/sh -c ['/root/start.sh']]
```

```
$ docker inspect --format="{{ .ContainerConfig.Cmd }}" test-labs:latest
[sh -c while true; do sleep 1; done]
```

```
$ docker run test-labs:latest
/bin/sh: 1: [/root/start.sh]: not found
```

```
$ docker ps --all
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                            PORTS               NAMES
1dcdfcdd85ce        test-labs:latest    "/bin/sh -c ['/root/s"   About a minute ago   Exited (127) About a minute ago                       big_einstein
```

**Comment by chouseknecht** [comment] 2016-08-11 23:17
@struongpax ansible-container seems to be working as expected.

`ansible-container run` runs the *command* found in container.yml. It does that regardless of the Config.Cmd value on the image. Of course, if there is NO *command* specified in container.yml, the Config.Cmd value will be executed, as demonstrated above. 

`andible-container build` builds the image and updates Config.Cmd on the committed image to the *command* specified in containery.yml. See [post_build method in contianer/docker/engine](https://github.com/ansible/ansible-container/blob/develop/container/docker/engine.py#L514) where this happens. And, as my tests demonstrated, that seems to be working.

Hopefully my explanation makes sense. I think we can say that ansible-container is working as expected. If I missed something, or if you have further questions, please feel free to re-open this issue.

**Closed by chouseknecht** 2016-08-11 23:17 UTC

**Comment by struongpax** [comment] 2016-08-22 20:38
Honestly I do not think that this is not a bug.  Here are what I  want to show that the bug is there.....
struong@mintlinux#0 filebeat ls
ansible  run

struong@mintlinux#0 filebeat pwd
/home/struong/ansible-container/filebeat
struong@mintlinux#0 filebeat cat run 
#!/bin/bash -e

rsync -av --exclude=*.swp ~/ansible/roles/filebeat/ ansible/roles/filebeat 

export DOCKER_HOST=tcp://172.17.0.1:7777

cid=$(docker ps -a|grep ansible_filebeat | grep Exited |awk '{print $1}')

echo $cid

if [ ! -z "$cid" ]; then
    echo "remove old container ansible_filebeat"
    docker rm -f $cid
fi

ansible-container --debug  build --from-scratch
if [ $? -eq 0 ]; then
    echo "Successfully build the container.  Deleting ansible/roles/*"
    rm -rf ansible/*.retry
    rm -rf ansible/roles/*
else
    echo "Failed to build the container"
fi

struong@mintlinux#0 filebeat ./run
sending incremental file list
created directory ansible/roles/filebeat
./
files/
files/beats.repo
tasks/
tasks/main.yml
templates/
templates/filebeat.yml.j2

sent 2,181 bytes  received 137 bytes  4,636.00 bytes/sec
total size is 1,796  speedup is 0.77

Project name is filebeat
Initialized with params: {'local_builder': False, 'rebuild': True, 'subcommand': 'build', 'engine_args': {'local_builder': False, 'engine_name': 'docker', 'rebuild': True, 'subcommand': 'build', 'engine_args': {...}, 'base_path': '/home/struong/ansible-container/filebeat', 'purge_last': True, 'ansible_options': u'', 'flatten': False, 'kwargs': {'debug': True, 'subcommand': 'build', 'no_purge_last': True}, 'debug': True, 'no_purge_last': True}, 'no_purge_last': True, 'ansible_options': u'', 'flatten': False, 'kwargs': {'debug': True, 'subcommand': 'build', 'no_purge_last': True}, 'debug': True, 'purge_last': True}
Using temporary directory /tmp/tmpVemsK9...
Starting Docker Compose engine to build your images...
Using temporary directory /tmp/tmpURjwo5...
Compose derived from config:
{'filebeat': {'image': 'centos:6.7', 'command': ['/bin/bash']}}
{'filebeat': {'image': 'centos:6.7', 'command': 'sh -c "while true; do sleep 1; done"', 'working_dir': '/', 'user': 'root'}}
Config YAML is
filebeat: {command: sh -c "while true; do sleep 1; done", image: 'centos:6.7', user: root,
  working_dir: /}

Rendered Jinja Template:
ansible-container:
  image: "ansible/ansible-container-builder:0.1"
  command: /usr/local/bin/builder.sh /usr/local/bin/ansible-playbook -i /etc/ansible/ansible-container-inventory.py -c docker  --list-hosts main.yml
  environment:
    - DOCKER_HOST
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
  volumes:
    
    - /home/struong/ansible-container/filebeat:/ansible-container/:Z
  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
filebeat: {command: sh -c "while true; do sleep 1; done", image: 'centos:6.7', user: root,
  working_dir: /}

Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
--list-hosts
ansible-container_1  | 
ansible-container_1  | playbook: main.yml
ansible-container_1  | 
ansible-container_1  |   play #1 (all): all	TAGS: []
ansible-container_1  |     pattern: [u'all']
ansible-container_1  |     hosts (1):
ansible-container_1  |       filebeat
ansible_ansible-container_1 exited with code 0
.....
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | filebeat                   : ok=7    changed=7    unreachable=0    failed=0   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 0
Aborting on container exit...
Stopping ansible_filebeat_1 ... done
Exporting built containers as images...
Committing image...
Exported filebeat-filebeat with image ID sha256:c1229bf9d5cb465dd481f4a79de3626553d5c7c334bfb892bd3460f12c6b0339
Cleaning up filebeat build container...
Removing previous image...
Cleaning up Ansible Container builder...
Cleaning up temporary directory /tmp/tmpVemsK9...
Successfully build the container.  Deleting ansible/roles/*
----
Here is my container.yml

version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  # web:
  #   image: ubuntu:trusty
  #   ports:
  #     - "80:80"
  #   command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
    filebeat:
        image: centos:6.7
        #ports:
        #    - "80:80"
        #entrypoint: ["/usr/local/bin/dumb-init", "--"]
        command: ["/bin/bash"]

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   

But I inspected the container image and the Cmd is not correct.

struong@mintlinux#0 filebeat docker inspect filebeat-filebeat
[
    {
        "Id": "sha256:c1229bf9d5cb465dd481f4a79de3626553d5c7c334bfb892bd3460f12c6b0339",
        "RepoTags": [
            "filebeat-filebeat:20160822203048",
            "filebeat-filebeat:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:ab3bca33ae3ceb4774eabdcaea60a06cc0fb547863a433524dc1283b5b68f15a",
        "Comment": "Built using Ansible Container",
        "Created": "2016-08-22T20:30:49.959726201Z",
        "Container": "0b5c9619a0a2af7696eedf195eeb4841c770a26f0e4d8d4664d6ceb2722b997f",
        "ContainerConfig": {
            "Hostname": "0b5c9619a0a2",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "sh",
                "-c",
                "while true; do sleep 1; done"
            ],
            "Image": "centos:6.7",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "License": "GPLv2",
                "Vendor": "CentOS",
                "com.docker.compose.config-hash": "80fa4264e6e51ce649458ecfdc2bdaf3c442d8f07166ccf2ac4fb7a17eb5fad5",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ansible",
                "com.docker.compose.service": "filebeat",
                "com.docker.compose.version": "1.7.0"
            }
        },
        "DockerVersion": "1.12.1",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "sh",
                "-c",
                "while true; do sleep 1; done"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "License": "GPLv2",
                "Vendor": "CentOS",
                "com.docker.compose.config-hash": "80fa4264e6e51ce649458ecfdc2bdaf3c442d8f07166ccf2ac4fb7a17eb5fad5",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ansible",
                "com.docker.compose.service": "filebeat",
                "com.docker.compose.version": "1.7.0"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 296157412,
        "VirtualSize": 296157412,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:69bd93b9db4e01f67316852e99bec9d8b3a657e0de17911994627360a16cb022",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:6dbd4eccb7b9dfef378dc9a2338ff8fae755809bf30ad4baa22a8755736bb412"
            ]
        }
    }
]

----
I have not upgraded docker or any other piece of software since the last time I filed this bug.

Please advise.

Thank you.

**Comment by chouseknecht** [comment] 2016-08-23 11:44
I'm running from the latest code found in the *develop* branch. 

container.yml:

```
version: "1"
services:
  filebeat:
    image: centos:6.7
    command: ["/bin/bash"]

registries: {}
```

main.yml

```
- hosts: all
  gather_facts: no
  tasks:
    - name: Say hi
      command: echo "hello!"
```

Inspect the image produced by `ansible-container build`:

```
$ docker inspect fix163-filebeat:latest
[
    {
        "Id": "sha256:2f83400e7c29bf739f4a58d6fccf9c0eb9c8345b5a3e6499f1fdbdba8db7b1cf",
        "RepoTags": [
            "fix163-filebeat:20160823051645",
            "fix163-filebeat:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:fb5054b394b7fcb824f9d54b93bb83de8a2308850129e3ecc5ad77f1c6ce5ce0",
        "Comment": "Built using Ansible Container",
        "Created": "2016-08-23T05:16:46.394653107Z",
        "Container": "4e5683dd883f2d127d6943477db0700d7b5973cb176bcf1deb1ef047c4b2ed45",
        "ContainerConfig": {
            "Hostname": "4e5683dd883f",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "sh",
                "-c",
                "while true; do sleep 1; done"
            ],
            "Image": "centos:6.7",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [],
            "OnBuild": null,
            "Labels": {
                "License": "GPLv2",
                "Vendor": "CentOS",
                "com.docker.compose.config-hash": "2c97f4017fb08f1c31c89ec024ce55c1df92cf3d05913189fcbb94e1578d8d73",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ansible",
                "com.docker.compose.service": "filebeat",
                "com.docker.compose.version": "1.7.0"
            }
        },
        "DockerVersion": "1.12.0",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "/bin/bash"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [],
            "OnBuild": null,
            "Labels": {
                "License": "GPLv2",
                "Vendor": "CentOS",
                "com.docker.compose.config-hash": "2c97f4017fb08f1c31c89ec024ce55c1df92cf3d05913189fcbb94e1578d8d73",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ansible",
                "com.docker.compose.service": "filebeat",
                "com.docker.compose.version": "1.7.0"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 190589267,
        "VirtualSize": 190589267,
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "409",
                "DeviceName": "docker-253:1-393503-eca0d7add4618ea21e886d6b4871e791d88a09c0cd6bb153eb17ccef29d086a2",
                "DeviceSize": "10737418240"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:d99d51992cfcef51bef6fa684bb10b13de0744c2858e39812fa925ddbb7d7f2f",
                "sha256:6e182660680483000fed7a2a7fff894165d7b35c6f034c448fbfdd4f277065b0"
            ]
        }
    }
]
```

**However**, if I run with ansible-container installed from PyPi, I do get the error. Here's the image inspection results:

```
$ docker inspect fix163-filebeat:latest
[
    {
        "Id": "sha256:67c1038c4233dd8a9b19b48e78ecde270cb9de3620749105b949706bcc2bb151",
        "RepoTags": [
            "fix163-filebeat:20160823052459",
            "fix163-filebeat:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:fb5054b394b7fcb824f9d54b93bb83de8a2308850129e3ecc5ad77f1c6ce5ce0",
        "Comment": "Built using Ansible Container",
        "Created": "2016-08-23T05:25:00.897640206Z",
        "Container": "653a026dea90d901cdd1746ac4ec8f4f9c63c2be56a27672e81d851da975b80c",
        "ContainerConfig": {
            "Hostname": "653a026dea90",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "sh",
                "-c",
                "while true; do sleep 1; done"
            ],
            "Image": "centos:6.7",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "License": "GPLv2",
                "Vendor": "CentOS",
                "com.docker.compose.config-hash": "157985b7708a578e4fd77d98bd4c4970050b12a6a31da718e549fcd25cb1ff40",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ansible",
                "com.docker.compose.service": "filebeat",
                "com.docker.compose.version": "1.7.0"
            }
        },
        "DockerVersion": "1.12.0",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "sh",
                "-c",
                "while true; do sleep 1; done"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "License": "GPLv2",
                "Vendor": "CentOS",
                "com.docker.compose.config-hash": "157985b7708a578e4fd77d98bd4c4970050b12a6a31da718e549fcd25cb1ff40",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ansible",
                "com.docker.compose.service": "filebeat",
                "com.docker.compose.version": "1.7.0"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 190589267,
        "VirtualSize": 190589267,
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "428",
                "DeviceName": "docker-253:1-393503-28b0f35e588b8718a311c32b50b6cadbf5c66b14a613238598889d559cd505a1",
                "DeviceSize": "10737418240"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:d99d51992cfcef51bef6fa684bb10b13de0744c2858e39812fa925ddbb7d7f2f",
                "sha256:e1d04c09b41c980262b751eba1e064416e66ee164ec1f2b9e4a133ae75713057"
            ]
        }
    }
]
```

**Comment by chouseknecht** [comment] 2016-08-23 11:47
I believe [this commit](https://github.com/ansible/ansible-container/commit/0b95fcd40eeae87bc85dc86cc04890e56117568a) fixed the issue you're experiencing. It is only available by running Ansible Container from source.
