### ISSUE TITLE
Ansible Container Installation Fails

### ISSUE THREAD

**Issue by coolsvap** [ansible/ansible-container#528] opened 2017-05-17 13:40 UTC
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
CentOS 7
```
##### SUMMARY
I am not able to install ansible-container pip package with the instructions provided in README

##### STEPS TO REPRODUCE

$ sudo pip install ansible-container

##### EXPECTED RESULTS
ansible-container should be installed

##### ACTUAL RESULTS
$ sudo pip install ansible-container
Collecting ansible-container
  Using cached ansible-container-0.9.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HNDRkd/ansible-container/setup.py", line 85, in <module>
        packages=find_packages(include='container.*'),
    TypeError: find_packages() got an unexpected keyword argument 'include'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HNDRkd/ansible-container/

**Comment by chouseknecht** [comment] 2017-05-17 13:45
@coolsvap, Thanks for using Ansible Container. We appreciate your feedback!

You likely need to upgrade setup tools. Try 'pip install --upgrade setuptools'

**Comment by chouseknecht** [comment] 2017-05-17 15:36
@coolsvap, I *think* this is a duplicate of #137, so closing for now. 

If you still encounter problems after upgrading `setuptools`, please add additional info/comments to this issue, and I'll re-open. 

Thanks!

**Closed by chouseknecht** 2017-05-17 15:36 UTC

**Comment by anquegi** [comment] 2018-08-03 11:50
I have the same problem on MAC  OSX

```
$  pip install --upgrade setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl (567kB)
    100% |████████████████████████████████| 573kB 1.2MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 39.2.0
    Uninstalling setuptools-39.2.0:
      Successfully uninstalled setuptools-39.2.0
Successfully installed setuptools-40.0.0
$ sudo pip install ansible-container[docker,k8s,openshift] 
The directory '/Users/toni/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/toni/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible-container[docker,k8s,openshift]
  Downloading https://files.pythonhosted.org/packages/bc/2a/b1252de3931173d26a30fc965be33c9cc0044cf7b23ce4c707f55d86830c/ansible-container-0.9.2.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.9MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-oRioDV/ansible-container/setup.py", line 10, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-oRioDV/ansible-container/
```

**Comment by Voronenko** [comment] 2018-08-03 11:53
@chouseknecht  Can you reach someone with access to pypi, so the 0.9.3 can be released?  Fix is already in develop, tests are green

**Comment by joaocc** [comment] 2018-08-29 13:10
Any news on this issue? I have the same problem with install on macOS 10.12.6, python 3.7.0, pip 18.0, setuptools 40.2.
```
$ pip3 install --upgrade ansible-container[docker,k8s]
Collecting ansible-container[docker,k8s]
  Using cached https://files.pythonhosted.org/packages/bc/2a/b1252de3931173d26a30fc965be33c9cc0044cf7b23ce4c707f55d86830c/ansible-container-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-install-lc3u9j3p/ansible-container/setup.py", line 10, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
```

**Comment by Voronenko** [comment] 2018-08-29 13:44
@joaocc Fixed in develop. Until that - workaround is to install ansible-container in virtual environment with pip downgraded to 9.0.3 ;

If you need assistance on that, let me know
