### ISSUE TITLE
pip install ansible-container FAIL in virtualenv

### ISSUE THREAD

**Issue by Ivan-Smagleson** [ansible/ansible-container#570] opened 2017-06-01 10:08 UTC
- Bug Report

##### OS / ENVIRONMENT

```
linux  3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

```
##### SUMMARY
unable to install ansible-container in virtualenv
 

##### STEPS TO REPRODUCE

```
$ virtualenv ansible-container
$ source ansible-container/bin/activate
$ pip install ansible-container

```

##### EXPECTED RESULTS

installed ansible-container
##### ACTUAL RESULTS

```
 pip install ansible-container
Downloading/unpacking ansible-container
  Downloading ansible-container-0.9.1.tar.gz (1.3MB): 1.3MB downloaded
  Running setup.py (path:/tmp/pip-build-GuWYPU/ansible-container/setup.py) egg_info for package ansible-container
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-GuWYPU/ansible-container/setup.py", line 50, in <module>
        install_requires=[str(ir.req) for ir in install_reqs if ir.match_markers()],
    AttributeError: 'InstallRequirement' object has no attribute 'match_markers'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-GuWYPU/ansible-container/setup.py", line 50, in <module>

    install_requires=[str(ir.req) for ir in install_reqs if ir.match_markers()],

AttributeError: 'InstallRequirement' object has no attribute 'match_markers'

----------------------------------------
```

**Comment by chouseknecht** [comment] 2017-06-01 14:58
@Ivan-Smagleson 

Thank you for using Ansible Container. We appreciate you taking the time to report this issue and share your feedback. 

It looks like you need to upgrade the version of pip you're running. That's my guess. `match_markers` is actually a method of the InstallRequiremet object, as you can see [here](https://github.com/pypa/pip/blob/0bdbee5c30c01f300e8c9c2545963406b3035c03/pip/req/req_install.py#L708).

Please try upgrading, and update this issue with the results. 

Thanks!

**Comment by Ivan-Smagleson** [comment] 2017-06-01 16:26
# pip install pip --upgrade
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages

what I do wrong?

**Comment by leki75** [comment] 2017-06-01 20:58
Debian 8 virtualenv, installed with apt, creates python environment with pip 1.5.6. That produces the same error you described.
```
root@dda49d54402b:/# cat /etc/debian_version
8.8

root@dda49d54402b:/# dpkg -l | grep virtualenv
ii  python-virtualenv          1.11.6+ds-1              all          Python virtual environment creator
ii  python3-virtualenv         1.11.6+ds-1              all          Python virtual environment creator
ii  virtualenv                 1.11.6+ds-1              all          Python virtual environment creator

root@dda49d54402b:/# virtualenv ansible-container
Running virtualenv with interpreter /usr/bin/python2
New python executable in ansible-container/bin/python2
Also creating executable in ansible-container/bin/python
Installing setuptools, pip...done.

root@dda49d54402b:/# source ansible-container/bin/activate

(ansible-container)root@dda49d54402b:/# pip list
argparse (1.2.1)
pip (1.5.6)
setuptools (5.5.1)
wsgiref (0.1.2)

(ansible-container)root@dda49d54402b:/# pip install ansible-container
Downloading/unpacking ansible-container
  Downloading ansible-container-0.9.1.tar.gz (1.3MB): 1.3MB downloaded
  Running setup.py (path:/tmp/pip-build-2TI_11/ansible-container/setup.py) egg_info for package ansible-container
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-2TI_11/ansible-container/setup.py", line 50, in <module>
        install_requires=[str(ir.req) for ir in install_reqs if ir.match_markers()],
    AttributeError: 'InstallRequirement' object has no attribute 'match_markers'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-2TI_11/ansible-container/setup.py", line 50, in <module>

    install_requires=[str(ir.req) for ir in install_reqs if ir.match_markers()],

AttributeError: 'InstallRequirement' object has no attribute 'match_markers'

----------------------------------------
Cleaning up...
```

If you upgrade pip the error message will disappear.
```
ansible-container)root@dda49d54402b:/# pip install -U pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...

(ansible-container)root@dda49d54402b:/# pip install ansible-container
Collecting ansible-container
  Using cached ansible-container-0.9.1.tar.gz
Collecting Jinja2>=2.9 (from ansible-container)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from ansible-container)
  Using cached PyYAML-3.12.tar.gz
Collecting requests>=2 (from ansible-container)
  Using cached requests-2.17.3-py2.py3-none-any.whl
Collecting ruamel.yaml>=0.14.2 (from ansible-container)
  Using cached ruamel.yaml-0.14.12-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six>=1.10 (from ansible-container)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting structlog[dev]>=16.1 (from ansible-container)
  Using cached structlog-17.2.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.9->ansible-container)
  Using cached MarkupSafe-1.0.tar.gz
Collecting urllib3<1.22,>=1.21.1 (from requests>=2->ansible-container)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests>=2->ansible-container)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2->ansible-container)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2->ansible-container)
  Using cached chardet-3.0.3-py2.py3-none-any.whl
Collecting ruamel.ordereddict (from ruamel.yaml>=0.14.2->ansible-container)
  Using cached ruamel.ordereddict-0.4.9-cp27-cp27mu-manylinux1_x86_64.whl
Collecting colorama; extra == "dev" (from structlog[dev]>=16.1->ansible-container)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Installing collected packages: MarkupSafe, Jinja2, PyYAML, urllib3, idna, certifi, chardet, requests, ruamel.ordereddict, ruamel.yaml, six, colorama, structlog, ansible-container
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for ansible-container ... done
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 PyYAML-3.12 ansible-container-0.9.1 certifi-2017.4.17 chardet-3.0.3 colorama-0.3.9 idna-2.5 requests-2.17.3 ruamel.ordereddict-0.4.9 ruamel.yaml-0.14.12 six-1.10.0 structlog-17.2.0 urllib3-1.21.1
```

What version of pip are you using?

**Comment by j00bar** [comment] 2017-06-02 20:30
This is a duplicate of #543

**Closed by j00bar** 2017-06-02 20:30 UTC
Labels: question
