### ISSUE TITLE
ansible-container fails on build, due to container.exceptions.AnsibleContainerDockerConnectionRefused

### ISSUE THREAD

**Issue by DamnedNForsaken** [ansible/ansible-container#602] opened 2017-06-12 23:16 UTC
- Bug Report

##### container.yml 

```

version: "2"
settings:
  conductor_base: centos:7
defaults:
  POSTGRES_USER: django
  POSTGRES_PASSWORD: sesame
  POSTGRES_DB: django
  DJANGO_PORT: 8080
services:
  django:
    from: centos:7
    roles:
      - django-gunicorn
    environment:
      DATABASE_URL: "pgsql://{{ POSTGRES_USER }}:{{ POSTGRES_PASSWORD }}@postgres:5432/{{ POSTGRES_DB }}"
      DJANGO_ROOT: '{{ DJANGO_ROOT }}'
      DJANGO_VENV: '{{ DJANGO_VENV }}'
    links:
    - postgres
    - postgres:postgresql
    ports:
    - '{{ DJANGO_PORT }}'
    working_dir: '{{ DJANGO_ROOT }}'
    user: '{{ DJANGO_USER }}'
    command: ['{{ DJANGO_VENV }}/bin/gunicorn', '-w', '2', '-b', '0.0.0.0:{{ DJANGO_PORT }}', 'project.wsgi:application']
    entrypoint: ['/usr/bin/dumb-init', '/usr/bin/entrypoint.sh']
    volumes:
      - 'static:{{ DJANGO_ROOT }}'
    dev_overrides:
      command: ['{{ DJANGO_VENV }}/bin/python', 'manage.py', 'runserver', '0.0.0.0:{{ DJANGO_PORT }}']
      volumes:
      - '${PWD}:{{ DJANGO_ROOT }}'
      - "static:/static"
      expose:
      - "{{ DJANGO_PORT }}"
      environment:
        DEBUG: "1"
  nginx:
    from: centos:7
    roles:
    - nginx
    ports:
    - '{{ DJANGO_PORT }}:8000'
    user: nginx
    links:
    - django
    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf']
    volumes:
    - 'static:{{ STATIC_ROOT }}'
    dev_overrides:
      ports: []
      command: /bin/false
      volumes: []
  postgres:
    from: postgres:9.6
    environment:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
volumes:
  static:
    docker: {}
registries: {}

```

##### OS / ENVIRONMENT

```
[root@localhost django-template]# ansible-container --debug version
Ansible Container, version 0.9.2rc0
Linux, localhost.localdomain, 3.10.0-514.el7.x86_64, #1 SMP Tue Nov 22 16:42:41 UTC 2016, x86_64
2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] /bin/python
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 0,
  "ContainerdCommit": {
    "Expected": "9048e5e50717ea4497b757314bad98ea3763c145",
    "ID": "9048e5e50717ea4497b757314bad98ea3763c145"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 25,
  "Swarm": {
    "ControlAvailable": false,
    "NodeID": "",
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "xfs"
    ],
    [
      "Supports d_type",
      "true"
    ]
  ],
  "OperatingSystem": "CentOS Linux 7 (Core)",
  "Containers": 0,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 1040871424,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-06-12T19:12:50.818118337-04:00",
  "Name": "localhost.localdomain",
  "CPUSet": true,
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": []
      }
    },
    "Mirrors": []
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 0,
  "NCPU": 1,
  "NFd": 17,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": false,
  "ID": "QSPL:FBOX:PJTQ:LS6Q:5IBZ:PKKG:C2VO:PJAR:J56S:ONP2:FT2H:27OF",
  "IPv4Forwarding": true,
  "KernelVersion": "3.10.0-514.el7.x86_64",
  "BridgeNfIptables": true,
  "NoProxy": "",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.05.0-ce",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": false,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": []
  },
  "Images": 19,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 0,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "9c2d8d184e5da67c95d601382adf14862e4f2228",
    "ID": "9c2d8d184e5da67c95d601382adf14862e4f2228"
  }
}
{
  "KernelVersion": "3.10.0-514.el7.x86_64",
  "Arch": "amd64",
  "BuildTime": "2017-05-04T22:06:25.279181930+00:00",
  "ApiVersion": "1.29",
  "Version": "17.05.0-ce",
  "MinAPIVersion": "1.12",
  "GitCommit": "89658be",
  "Os": "linux",
  "GoVersion": "go1.7.5"
}

```
##### SUMMARY
I am unable to build the example ansible-container image.
I have attempted to get the most updated everything and I am still unable to build this.

##### STEPS TO REPRODUCE

#update and init apps
sudo yum -y update
sudo yum -y install git
sudo yum -y install wget

#get docker and install/setup it
wget http://get.docker.com
sudo chmod 777 index.html
sudo ./index.html
sudo usermod -aG docker admin

#get dependencies required for ansible-container
sudo yum -y install epel-release
sudo yum -y install ansible
sudo yum -y install python-pip
sudo yes | sudo pip install --upgrade pip
sudo yes | sudo pip install --upgrade setuptools
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
sudo yum install python-devel
sudo yes | sudo pip install ansible-container[docker]
sudo yes | sudo pip uninstall ansible-container

#build ansible-container from source
mkdir source
cd source
git clone https://github.com/ansible/ansible-container
cd ansible-container
sudo make

#modify the systemd file so that has ssh intro
cat - <<EOF | sudo tee /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service
Wants=network-online.target
[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/docker daemon -H 0.0.0.0:2375
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s
EOF

#systemd and ENV var setup
sudo systemctl daemon-reload
export DOCKER_HOST="tcp://127.0.0.1:2375"
sudo systemctl enable docker
sudo systemctl start docker
sudo systemctl restart docker

#check
sudo systemctl status docker
docker ps -a
docker images -a

#make a test
cd ../../
mkdir init
cd init
ansible-container init ansible.django-template
ansible-container build
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^breaks here.
ansible-container run

#status checks
docker images -a
docker ps -a
```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
An built ansible-container

##### ACTUAL RESULTS
2017-06-12T23:11:16.096697 Building service...            [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=639 project=django-template service=u'django'
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 366, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 640, in conductorcmd_build
    cur_image_id = engine.get_image_id_by_tag(service['from'])
  File "/_ansible/container/docker/engine.py", line 440, in get_image_id_by_tag
    image = self.client.images.get(tag)
  File "/_ansible/container/docker/engine.py", line 126, in client
    raise exceptions.AnsibleContainerDockerConnectionRefused()
container.exceptions.AnsibleContainerDockerConnectionRefused
2017-06-12T19:11:16.289203 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/home/admin/source/ansible-container/container/docker/engine.py caller_func=await_conductor_command caller_line=353 command_rc=1 conductor_id=u'23d53b32a3d5610e92af4fe6b927087d3a1291215caa6474887041a7ae8a7d33' save_container=False
2017-06-12T19:11:18.178314 Conductor exited with status 1 [container.cli] caller_file=/home/admin/source/ansible-container/container/cli.py caller_func=__call__ caller_line=286
[

**Comment by DamnedNForsaken** [comment] 2017-06-12 23:50
Also please note: that yes i am:
sudo yes | sudo pip install ansible-container[docker]
sudo yes | sudo pip uninstall ansible-container
but then i make from source...
I needed to do i this way because without the build from source (latest) I was running into a:latest errors, and also I needed to run the pip because if i recall without doing the pip as well i was getting the no connector error....

I am not sure what is happening here, but I am assuming that the install of ansible-container[docker] supplies the connector dependencies?

Regardless I believe that my ansible-container application is working fine.. but my there is something wrong with my build now... 

this could possibly be related to: https://github.com/ansible/ansible-container/issues/448
Because I see the 'From" error there... However i have pulled the latest ansible-container django-template from source and I am still seeing this error... so like wtf am I doing wrong??
-Best

**Comment by chouseknecht** [comment] 2017-06-14 13:17
@DamnedNForsaken 

Thanks for your interest in Ansible Container. We appreciate you taking the time to try it out, and sharing your feedback. 

I suspect you're not actually running from source. Our Makefile is actually wrong, and needs to be updated. 

Please uninstall Ansible Container, and then in the root of the cloned directory, run the following:

```
$ pip install -e .[docker,openshift]
```

**Comment by DamnedNForsaken** [comment] 2017-06-14 20:15
Hi @chouseknecht 

NO that has not worked. I ran the following and still it gives the same error... Maybe I am doing something wrong still?
`#bin/bash
# a file to install ansible-container and required dependencies
# by Mark Schafer <ms2236@att.com>

#update and init apps
sudo yum -y update
sudo yum -y install git
sudo yum -y install wget

#get docker and install/setup it
wget http://get.docker.com
sudo chmod 777 index.html
sudo ./index.html
sudo usermod -aG docker admin

#get dependencies required for ansible-container
sudo yum -y install epel-release
sudo yum -y install ansible
sudo yum -y install python-pip
sudo yes | sudo pip install --upgrade pip
sudo yes | sudo pip install --upgrade setuptools
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
sudo yum install python-devel
#i bet can remove the ansible container part and just keep the docker....
sudo yes | sudo pip install ansible-container[docker]
sudo yes | sudo pip uninstall ansible-container

#build ansible-container from source
mkdir source
cd source
git clone https://github.com/ansible/ansible-container
cd ansible-container
sudo yes | sudo pip install -e .[docker,openshift]
#sudo make   per the @chouseknect@github this is not updated...  so the above step should make it...

#modify the systemd file so that has ssh intro
cat - <<EOF | sudo tee /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service
Wants=network-online.target
[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/docker daemon -H 0.0.0.0:2375
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s
EOF

#systemd and ENV var setup
sudo systemctl daemon-reload
export DOCKER_HOST="tcp://127.0.0.1:2375"
sudo systemctl enable docker
sudo systemctl start docker
sudo systemctl restart docker

#check
sudo systemctl status docker
docker ps -a
docker images -a

#make a test
cd ../../
mkdir init
cd init
ansible-container init ansible.django-template
ansible-container build
ansible-container run

#status checks
docker images -a
docker ps -a`

**Comment by DamnedNForsaken** [comment] 2017-06-14 20:27
has failed with:
[admin@localhost init]$ ansible-container build
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
Parsing conductor CLI args.
Docker™ daemon integration engine loaded. Build starting.       project=init
Building service...     project=init service=django
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 366, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 640, in conductorcmd_build
    cur_image_id = engine.get_image_id_by_tag(service['from'])
  File "/_ansible/container/docker/engine.py", line 440, in get_image_id_by_tag
    image = self.client.images.get(tag)
  File "/_ansible/container/docker/engine.py", line 126, in client
    raise exceptions.AnsibleContainerDockerConnectionRefused()
container.exceptions.AnsibleContainerDockerConnectionRefused
Conductor terminated. Cleaning up.      command_rc=1 conductor_id=4ab530482505fc508e2ee982d1815c1991037332eb81a009adce3f6d9841c951 save_container=False
ERROR   Conductor exited with status 1

**Comment by chouseknecht** [comment] 2017-06-15 14:50
I wonder if the issue is `ExecStart=/usr/bin/docker daemon -H 0.0.0.0:2375`

In order for the playbook to run inside the conductor and execute tasks on the service container, the Docker connection plugin needs to access the Docker Daemon.

You're setting DOCKER_HOST="127.0.0.1:2375". From inside the conductor, "127.0.0.1" likely doesn't work. It would just point back to the conductor. Instead, it needs to point to the host machine. I would set this to the IP address of the host, or just use the default Unix socket connection, rather than TCP.

**Comment by DamnedNForsaken** [comment] 2017-06-15 16:31
OK, will try that. The reason that I had set the env variable and the systemd that way was due to this article:
[](https://tech.napsty.com/2016/06/using-ansible-to-build-and-orchestrate-clean-docker-images.html)

**Comment by DamnedNForsaken** [comment] 2017-06-15 17:21
Yay! That totally worked!! :)
So i just changed the env var, and the systemd start exec line to (respectfully):
export DOCKER_HOST="unix:///var/run/docker.sock"
ExecStart=/usr/bin/docker daemon -H unix:///var/run/docker.sock

Yeah, normally i see the docker ssh port appended to the systemd... there is alot of misleading ansible-container info out there presently... I blame alot of this on the name.... ansible-container search results always bring up "ansible in containers" etc... you guys/gals should really think of a better name (but thats just my two cents)

Well it is not all good news as I am able to get the default Nginx container to run, as after the run step is has "Exited" status. I wonder what could be causing this... But as the build issue is solved I believe this ticket is done. I will look at the run step alittle more and worse come to worse send another ticket through. 

Thanks @chouseknecht :+1: 
Best!

**Comment by chouseknecht** [comment] 2017-06-15 22:00
Because of the `dev_overrides` section in `nginx`, that service is not expected to run. Notice `command` is set to `/bin/false`. That causes it to exit immediately with an exit code of 1 when you `ansible-container run`.

Closing this, since I believe we have solved the main problem.

**Closed by chouseknecht** 2017-06-15 22:00 UTC
Labels: bug
