### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Raffaello** [ansible/ansible-container#631] opened 2017-06-30 09:47 UTC
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT
```
fedora 25
ansible 2.3.1.0
python 2.7.7
```
##### SUMMARY
cannot install here the output:
```bash
sudo pip install ansible-container

Collecting ansible-container
  Downloading ansible-container-0.9.1.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.4MB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zmkoll/ansible-container/setup.py", line 84, in <module>
        packages=find_packages(include='container.*'),
    TypeError: find_packages() got an unexpected keyword argument 'include'

```

##### STEPS TO REPRODUCE

just the install step has failed

```
sudo pip install ansible-container
```

##### EXPECTED RESULTS

installed

##### ACTUAL RESULTS

failed.

```
did already.
```

**Comment by chouseknecht** [comment] 2017-07-05 13:47
@Raffaello 

Thanks for trying Ansible Container, and sharing your feedback!

This has been addressed previously. You need to upgrade setuptools. Try running the following:

```
$ sudo pip install --upgrade setuptools
```

**Comment by chouseknecht** [comment] 2017-07-05 13:51
Duplicate of #137

**Closed by chouseknecht** 2017-07-05 13:51 UTC

**Comment by Raffaello** [comment] 2017-07-08 12:52
@chouseknecht Thanks! 
may I suggest to add as a "troubleshooting" section in the README this aspect?
