### ISSUE TITLE
Unable to install ansible-container[openshift], due to requirement of openshift=1.0.0 instead of openshift=0.0.1

### ISSUE THREAD

**Issue by jwmatthews** [ansible/ansible-container#530] opened 2017-05-17 18:56 UTC
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
$ ansible-container --debug version
Ansible Container, version 0.9.0.0
Linux, beast.localdomain, 4.9.14-200.fc25.x86_64, #1 SMP Mon Mar 13 19:26:40 UTC 2017, x86_64
2.7.13 (default, Jan 12 2017, 17:59:37) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] /home/jmatthews/playpen/ansible-container/bin/python
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "DefaultRuntime": "oci", 
  "CgroupDriver": "systemd", 
  "ClusterAdvertise": "", 
  "ContainersRunning": 14, 
  "NGoroutines": 88, 
  "Swarm": {
    "Managers": 0, 
    "ControlAvailable": false, 
    "NodeID": "", 
    "Cluster": {
      "Spec": {
        "Raft": {}, 
        "CAConfig": {}, 
        "Dispatcher": {}, 
        "Orchestration": {}, 
        "TaskDefaults": {}
      }, 
      "Version": {}, 
      "ID": "", 
      "CreatedAt": "0001-01-01T00:00:00Z", 
      "UpdatedAt": "0001-01-01T00:00:00Z"
    }, 
    "Nodes": 0, 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "journald", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "oci": {
      "path": "/usr/libexec/docker/docker-runc-current"
    }, 
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Pool Name", 
      "docker-253:0-8652095-pool"
    ], 
    [
      "Pool Blocksize", 
      "65.54 kB"
    ], 
    [
      "Base Device Size", 
      "10.74 GB"
    ], 
    [
      "Backing Filesystem", 
      "xfs"
    ], 
    [
      "Data file", 
      "/dev/loop0"
    ], 
    [
      "Metadata file", 
      "/dev/loop1"
    ], 
    [
      "Data Space Used", 
      "19.71 GB"
    ], 
    [
      "Data Space Total", 
      "107.4 GB"
    ], 
    [
      "Data Space Available", 
      "87.67 GB"
    ], 
    [
      "Metadata Space Used", 
      "30.2 MB"
    ], 
    [
      "Metadata Space Total", 
      "2.147 GB"
    ], 
    [
      "Metadata Space Available", 
      "2.117 GB"
    ], 
    [
      "Thin Pool Minimum Free Space", 
      "10.74 GB"
    ], 
    [
      "Udev Sync Supported", 
      "true"
    ], 
    [
      "Deferred Removal Enabled", 
      "false"
    ], 
    [
      "Deferred Deletion Enabled", 
      "false"
    ], 
    [
      "Deferred Deleted Device Count", 
      "0"
    ], 
    [
      "Data loop file", 
      "/var/lib/docker/devicemapper/devicemapper/data"
    ], 
    [
      "Metadata loop file", 
      "/var/lib/docker/devicemapper/devicemapper/metadata"
    ], 
    [
      "Library Version", 
      "1.02.136 (2016-11-05)"
    ]
  ], 
  "OperatingSystem": "Fedora 25 (Twenty Five)", 
  "Containers": 84, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 135126466560, 
  "Driver": "devicemapper", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "ExecutionDriver": "", 
  "Registries": [
    {
      "Name": "docker.io", 
      "Secure": true
    }
  ], 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "PkgVersion": "docker-common-1.12.6-6.gitae7d637.fc25.x86_64", 
  "SystemTime": "2017-05-17T14:52:59.185245332-04:00", 
  "Name": "beast.localdomain", 
  "CPUSet": true, 
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "172.30.0.0/16", 
      "127.0.0.0/8"
    ], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": null
      }
    }, 
    "Mirrors": null
  }, 
  "SecurityOptions": [
    "seccomp", 
    "selinux"
  ], 
  "ContainersStopped": 70, 
  "NCPU": 16, 
  "NFd": 84, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "IndexServerName": "docker.io", 
  "ID": "2I3J:Q35I:H2QW:VEOG:MMAO:ZSA4:F73D:E7RD:UF2G:XC3M:IQHS:2EAH", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.9.14-200.fc25.x86_64", 
  "BridgeNfIptables": true, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "1.12.6", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": true, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "bridge", 
      "host", 
      "null", 
      "overlay"
    ], 
    "Authorization": null
  }, 
  "Images": 73, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 0, 
  "CPUShares": true
}
{
  "KernelVersion": "4.9.14-200.fc25.x86_64", 
  "PkgVersion": "docker-common-1.12.6-6.gitae7d637.fc25.x86_64", 
  "Os": "linux", 
  "BuildTime": "2017-01-30T16:15:28.001305301+00:00", 
  "ApiVersion": "1.24", 
  "Version": "1.12.6", 
  "GitCommit": "ae7d637/1.12.6", 
  "Arch": "amd64", 
  "GoVersion": "go1.7.4"
}

```
##### SUMMARY

pip install ansible-container[openshift]  fails, unable to find openshift=1.0.0

##### STEPS TO REPRODUCE

```
 pip install ansible-container[openshift]
Requirement already satisfied: ansible-container[openshift] in /home/jmatthews/playpen/ansible-container/lib/python2.7/site-packages
Requirement already satisfied: six>=1.10 in /home/jmatthews/playpen/ansible-container/lib/python2.7/site-packages (from ansible-container[openshift])
Requirement already satisfied: PyYAML>=3.12 in /home/jmatthews/playpen/ansible-container/lib/python2.7/site-packages (from ansible-container[openshift])
Requirement already satisfied: ruamel.yaml>=0.14.2 in /home/jmatthews/playpen/ansible-container/lib/python2.7/site-packages (from ansible-container[openshift])
Requirement already satisfied: Jinja2>=2.9 in /home/jmatthews/playpen/ansible-container/lib/python2.7/site-packages (from ansible-container[openshift])
Requirement already satisfied: requests>=2 in /home/jmatthews/playpen/ansible-container/lib/python2.7/site-packages (from ansible-container[openshift])
Requirement already satisfied: structlog[dev]>=16.1 in /home/jmatthews/playpen/ansible-container/lib/python2.7/site-packages (from ansible-container[openshift])
Collecting openshift==1.0.0; extra == "openshift" (from ansible-container[openshift])
  Could not find a version that satisfies the requirement openshift==1.0.0; extra == "openshift" (from ansible-container[openshift]) (from versions: 0.0.1)
No matching distribution found for openshift==1.0.0; extra == "openshift" (from ansible-container[openshift])

```

##### EXPECTED RESULTS

Assume this has already been fixed in master just needs to a new release to pypi to pick it up:
https://github.com/ansible/ansible-container/blob/develop/setup.py#L60

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment] 2017-05-17 19:52
@jwmatthews, thanks for using Ansible Container. We appreciate your feedback!

Closing, as this is a duplicate of #487. 

The issue has been fixed in the the `develop` branch, but a new release has not been pushed to PyPi. To get the latest code with the fix, you'll need to install from source. For assistance, please see our [running from source guide](http://docs.ansible.com/ansible-container/installation.html#running-from-source).

**Closed by chouseknecht** 2017-05-17 19:52 UTC
