### ISSUE TITLE
Use ansible 2.0.2.0 to avoid bug with s3 in 2.1.0.0

### ISSUE THREAD

**Issue by splisson-altair** [ansible/ansible-container#151] opened 2016-08-05 21:12 UTC
##### ISSUE TYPE
 - Bug Report

##### OS / ENVIRONMENT

```
Ansible Container, version 0.1.0
Darwin, camac06.home, 15.6.0, Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64, x86_64
2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] /usr/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 147,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 147,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'449'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': True,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'PWG4:VIOF:YMSH:3LWM:BVC6:TXH3:FD6W:DR7I:QQ7F:UBVM:Z3R4:RWIZ',
 u'IPv4Forwarding': True,
 u'Images': 166,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.4.15-moby',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 2097557504,
 u'MemoryLimit': True,
 u'NCPU': 4,
 u'NEventsListener': 1,
 u'NFd': 30,
 u'NGoroutines': 41,
 u'Name': u'moby',
 u'NoProxy': u'*.local, 169.254/16',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Alpine Linux v3.4',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'overlay', u'host', u'bridge', u'null'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.0',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-08-05T21:10:07.92948506Z'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-07-28T21:04:48.864474905+00:00',
 u'Experimental': True,
 u'GitCommit': u'8eab29e',
 u'GoVersion': u'go1.6.3',
 u'KernelVersion': u'4.4.15-moby',
 u'Os': u'linux',
 u'Version': u'1.12.0'}
```
##### SUMMARY
Ansible version 2.1.0 has a bug with s3 module
https://github.com/ansible/ansible-modules-core/issues/3447

##### STEPS TO REPRODUCE
Using s3 module will not be able to get files

##### EXPECTED RESULTS
Able to use s3 module

##### ACTUAL RESULTS
```
FAILED! => {"changed": false, "failed": true, "msg": "Failed to connect to S3: Region  does not seem to be available for aws module boto.s3. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path"}
```

**Comment by splisson-altair** [comment] 2016-08-05 23:29
changed the source code of ansible-container locally to use ansible 2.0.2.0 and run 
`ansible-container build --local-builder` to build the image locally

now I get
(Re)building the Ansible Container image.
Building Docker Engine context...
Starting Docker build of Ansible Container image (please be patient)... ansible-container-builder
No image with the name ansible-container-builder

**Comment by chouseknecht** [comment] 2016-08-08 19:42
Duplicate of #150.

**Closed by chouseknecht** 2016-08-08 19:42 UTC
