### ISSUE TITLE
docker-compose complains about missing 'splitdrive' module

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#720] opened 2017-09-09 00:17 UTC
From IRC conversation:

```
2:36 PM A<aric49> Happy Friday everyone!
2:37 PM Running into a rather bizarre docker-compose split-drive error when I try to run a build. Has anyone seen this before:
2:39 PM FAILED! => {"changed": false, "failed": true, "msg": "Unable to load docker-compose. Try `pip install docker-compose`. Error: cannot import name splitdrive"}
2:40 PM i tried uninstalling the pip package i have installed for docker compose, also uninstalling and reinstalling ansible-container from pip. No dice
3:36 PM A<aric49> further research shows this might be an issue with Docker Compose itself: https://github.com/docker/compose/issues/5156

5:02 PM J<•j00bar> jag aric49: yeah, i ran into that yesterday on one of my builds. i was going to dig into it but haven't had the chance yet

5:02 PM chouseknecht: --^^
5:20 PM C<•chouseknecht> ack
5:20 PM Will look
```

**Comment by chouseknecht** [comment] 2017-09-09 00:20
Attempting to reproduce on macOS. 

- Created clean virtualenv
- Ran `pip install ansible-container[docker,k8s]`

The above results in the install of `docker` Python module, rather than `docker-compose`, and a `build` works fine.

**Comment by chouseknecht** [comment] 2017-09-09 00:24
Ran the following:

- pip uninstall docker
- pip install docker-compose

The above results in the following Docker Python modules installed:

```
docker (2.5.1)
docker-compose (1.16.1)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
```

**Comment by chouseknecht** [comment] 2017-09-09 00:30
Ran the following: 

- pip uninstall docker 
- pip install docker-py

Which results in the following Docker Python modules installed:

```
docker-compose (1.16.1)
docker-py (1.10.6)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
```

**Comment by amoravek** [comment] 2017-09-10 14:36
Ran into the same issue. Nothing (reinstalling docker/docker-py/docker-compose, etc) helped. I am not able to use the ansible-container at all now.

**Comment by aric49** [comment] 2017-09-10 23:12
Since I am the one who unofficially reported this issue on IRC (Thanks @chouseknecht! I was literally going onto Github to report this just now :+1: ), I have done some further experimentation.  It appears that this issue does seem to be present in pretty much all the conductor images that get built (CentOS, Ubuntu, etc).   I have tried manually going inside the conductor images and uninstalling and re-installing docker-compose and various versions (1.15.0, 1.8.0) via Pip, re-commiting the container images and have not yet had any success getting it to run. I will keep testing out different combinations and see if I can get it working in my local environment.

**Comment by chouseknecht** [comment] 2017-09-11 12:08
Still not able to reproduce this. 

- Running with the latest source from the `develop` branch. 
- Removed all existing containers via `docker rm --force $(docker ps -qa)`
- Removed all images via `docker rmi --force $(docker images -qa)`

Here's my environment:

```
(pcvenv) ~/projects/test $ ansible-container --debug version
Ansible Container, version 0.9.2rc0
Darwin, Chriss-MacBook-Pro-2.local, 15.6.0, Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64, x86_64
2.7.12 (default, Oct 11 2016, 05:24:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] /Users/chouseknecht/projects/pcvenv/bin/python2.7
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 0,
  "ContainerdCommit": {
    "Expected": "3addd840653146c90a254301d6c3a663c7fd6429",
    "ID": "3addd840653146c90a254301d6c3a663c7fd6429"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 31,
  "Swarm": {
    "ControlAvailable": false,
    "NodeID": "",
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "OperatingSystem": "Alpine Linux v3.5",
  "Containers": 0,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 2095878144,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay2",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-09-11T12:04:33.096733323Z",
  "Name": "moby",
  "CPUSet": true,
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "Mirrors": [],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": []
      },
      "local.openshift": {
        "Official": false,
        "Name": "local.openshift",
        "Secure": false,
        "Mirrors": []
      }
    },
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 0,
  "NCPU": 4,
  "NFd": 19,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "7YJP:2A67:F7CQ:4XLN:R3N5:L7CG:7S5J:RDU6:KOPV:AUE5:BHDP:LKGF",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.41-moby",
  "BridgeNfIptables": true,
  "NoProxy": "*.local, 169.254/16",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.07.0-ce-rc2",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": true,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "Images": 65,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 1,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "2d41c047c83e09a6d61d464906feb2a2f3c52aa4",
    "ID": "2d41c047c83e09a6d61d464906feb2a2f3c52aa4"
  }
}
{
  "KernelVersion": "4.9.41-moby",
  "Arch": "amd64",
  "BuildTime": "2017-08-07T23:48:34.099516076+00:00",
  "ApiVersion": "1.31",
  "Version": "17.07.0-ce-rc2",
  "MinAPIVersion": "1.12",
  "GitCommit": "36ce605",
  "Os": "linux",
  "Experimental": true,
  "GoVersion": "go1.8.3"
}
```

@aric49 
@amoravek 

Please share the output from `ansible-container --debug version`

Thanks!

**Comment by chouseknecht** [comment] 2017-09-11 12:13
@aric49
@amoravek

My test case is using `centos:7`. Which base are you using?

And which version of the Docker Python module do you have installed? 

Here's what's in my environment:

```
$ pip list | grep docker

docker (2.5.1)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
```

**Comment by amoravek** [comment] 2017-09-11 13:40
My environment is:

ansible-container --debug version
==========================
Ansible Container, version 0.9.1
Linux, lenovo, 4.10.0-33-generic, #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /usr/bin/python
ERROR	No Ansible Container project data found - do you need to run "ansible-container init"?	

pip list | grep docker
===============
docker (2.5.1)
docker-py (1.10.6)
docker-pycreds (0.2.1)
dockerpty (0.4.1)

conductor image:

docker version
============
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      linux/amd64

docker-compose version
===================
docker-compose version 1.16.1, build 6d1ac219
docker-py version: 2.5.1
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by ryansb** [comment] 2017-09-11 16:44
This is probably the core of the issue: 

```
docker (2.5.1)
docker-py (1.10.6)
```

The two Docker python libraries are (unfortunately) not co-installable, so the source of the issue is very likely that the `docker-py` package is installed alongside the new 2.0 SDK.

**Comment by j00bar** [comment] 2017-09-11 18:50
I believe this is a breaking change introduced in Compose prior to 1.16 - the problem is a circular import. Those who can reproduce the issue, please rebuild your conductors (do a build with `--no-conductor-cache`) after modifying `container/docker/files/conductor-requirements.txt` in your installation by changing `docker-compose>=1.14` to `docker-compose>=1.14,<1.16`.

**Comment by aric49** [comment] 2017-09-11 21:43
Sorry for the late response. Busy day today with work.   To clarify, I am seeing this issue after the build stage, and when I attempt an `ansible-container run` on my project.   The error I am seeing is below:

```
ubuntu@node01:/vagrant/AnsibleContainer/mariadb_demo$ ansible-container run
Parsing conductor CLI args.
Engine integration loaded. Preparing run.       engine=Docker™ daemon
Verifying service image service=mysql_database_container

PLAY [localhost] ***************************************************************

TASK [docker_service] **********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to load docker-compose. Try `pip install docker-compose`. Error: cannot import name splitdrive"}
        to retry, use: --limit @/vagrant/AnsibleContainer/mariadb_demo/ansible-deployment/playbook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

All services running.   playbook_rc=2
Conductor terminated. Cleaning up.      command_rc=0 conductor_id=4a461b895e380776a9d450021565bf552b1510e89fd33d79003010d6724cd66a save_container=False
ubuntu@node01:/vagrant/AnsibleContainer/mariadb_demo$
```

Here are my Ansible Container environment details:
```
Ansible Container, version 0.9.1
Linux, node01, 4.4.0-93-generic, #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /usr/bin/python
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "DefaultRuntime": "runc", 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 1, 
  "NGoroutines": 28, 
  "Swarm": {
    "Managers": 0, 
    "ControlAvailable": false, 
    "NodeID": "", 
    "Cluster": {
      "Spec": {
        "Raft": {}, 
        "CAConfig": {}, 
        "Dispatcher": {}, 
        "Orchestration": {}, 
        "TaskDefaults": {}
      }, 
      "Version": {}, 
      "ID": "", 
      "CreatedAt": "0001-01-01T00:00:00Z", 
      "UpdatedAt": "0001-01-01T00:00:00Z"
    }, 
    "Nodes": 0, 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "runc"
    }
  }, 
  "DriverStatus": [
    [
      "Root Dir", 
      "/var/lib/docker/aufs"
    ], 
    [
      "Backing Filesystem", 
      "extfs"
    ], 
    [
      "Dirs", 
      "31"
    ], 
    [
      "Dirperm1 Supported", 
      "true"
    ]
  ], 
  "OperatingSystem": "Ubuntu 16.04.3 LTS", 
  "Containers": 2, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 1040330752, 
  "Driver": "aufs", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "ExecutionDriver": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-09-11T21:32:19.386614518Z", 
  "Name": "node01", 
  "CPUSet": true, 
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": null
      }
    }, 
    "Mirrors": null
  }, 
  "SecurityOptions": [
    "apparmor", 
    "seccomp"
  ], 
  "ContainersStopped": 1, 
  "NCPU": 2, 
  "NFd": 21, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "ID": "JMFB:73FV:IOMM:OT3G:VWUM:BWCH:K6IT:QM6F:XHUH:YU4X:2KQF:4ZEY", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.4.0-93-generic", 
  "BridgeNfIptables": true, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "1.12.6", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": false, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "host", 
      "bridge", 
      "overlay", 
      "null"
    ], 
    "Authorization": null
  }, 
  "Images": 26, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 0, 
  "CPUShares": true
}
{
  "KernelVersion": "4.4.0-93-generic", 
  "Os": "linux", 
  "BuildTime": "2017-01-31T23:35:14.312544877+00:00", 
  "ApiVersion": "1.24", 
  "Version": "1.12.6", 
  "GitCommit": "78d1802", 
  "Arch": "amd64", 
  "GoVersion": "go1.6.2"
}
```

Here are my Pip docker packages:
```
ubuntu@node01:/vagrant/AnsibleContainer/mariadb_demo$ pip list | grep docker
docker (2.5.1)
docker-compose (1.8.0)
docker-py (1.9.0)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
```

@j00bar  -- Thanks for the suggestion.  excuse my ignorance, but where is the `container/docker/files/conductor-requirements.txt` file you're referring to?  Using  `find` i can see that it is located in my environment at:  `/usr/local/lib/python2.7/dist-packages/container/docker/files/conductor-requirements.txt`

However, the contents of that file is:
```
ubuntu@node01:/vagrant/AnsibleContainer/mariadb_demo$ cat /usr/local/lib/python2.7/dist-packages/container/docker/files/conductor-requirements.txt
#https://github.com/ansible/ansible/archive/devel.tar.gz
ansible>=2.3.0
https://github.com/openshift/openshift-restclient-python/archive/master.tar.gz#egg=openshift-1.0.0
PyYAML>=3.12
docker-compose>=1.7
requests>=2
ruamel.yaml>=0.14.2
six>=1.10
structlog[dev]>=16.1
python-string-utils>=0.6.0
```

Thanks for the help everyone.  If you want, you can clone my vagrant lab and re-create the issue:  
```
git clone git@github.com:aric49/ansible_container_lab.git
cd ansible_container_lab
vagrant up
#Vagrant VM builds and comes up
vagrant ssh node01
cd /vagrant/AnsibleContainer/mariadb_demo/
ansible-container build
ansible-container run
```

Super appreciate all the help and support on this!

**Comment by amoravek** [comment] 2017-09-11 21:43
What do you mean by 'modifying container/docker/files/conductor-requirements.txt'? Do you mean modifying file '/_ansible/container/docker/files/conductor-requirements.txt' inside the conductor image?
If so, there was not the version 1.7, but 1.14 (docker-compose>=1.14).
I've changed it according to your recommendation, commited the container back to the conductor image (docker commit) and re-run the 'ansible-container run'. unfortunately without success.

**Comment by j00bar** [comment] 2017-09-11 21:54
Howdy!

So when you do an `ansible-container build` on 0.9.1, the first thing it does is (re)build the Conductor image. The context of that Conductor image includes what gets installed on your controller host as `$PYTHONHOME/site-packages/container/docker/files/conductor-requirements.txt` (see https://github.com/ansible/ansible-container/blob/release-0.9.1/container/docker/engine.py#L687-688), and the Conductor image build `pip install -r`'s that file (see https://github.com/ansible/ansible-container/blob/release-0.9.1/container/docker/templates/conductor-dockerfile.j2#L46). So if you modify the file on your controller inside of your `site-packages` and rebuild your Conductor image, it should naturally process that.

After your build, you can check to make sure that everything was processed correctly with:
`docker run -it --rm mariadb_demo-conductor pip freeze` and `grep` for `docker-compose` (presuming that's what your Conductor image gets tagged).

**Comment by j00bar** [comment] 2017-09-12 01:59
Okay, yeah. In my testing, this affects Ansible 2.3.x with Docker Compose >= 1.16, and since 0.9.1 shipped with the Conductor containing Ansible 2.3.x, we can't really fix this for that release.

We'll be pushing a 0.9.2 in the next 24 hrs. In the meantime, my manual edit above should fix things for 0.9.1 folks, or upgrade to the latest devel (which also means you'll be using prebaked conductors).

**Comment by j00bar** [comment] 2017-09-12 14:22
This issue should be resolved in 0.9.2 - please reopen if you find it is not. Thanks!

**Closed by j00bar** 2017-09-12 14:22 UTC
Labels: bug

**Comment by amoravek** [comment] 2017-09-12 14:52
Ok, thank you

**Comment by jschulthess** [comment] 2017-09-12 17:25
Using 0.9.2, a task like the following:
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present
fails with:
fatal: [elasticsearch]: FAILED! => {"changed": false, "failed": true, "msg": "gpg: no valid OpenPGP data found.\ngpg: processing message failed: Unknown system error\n"}

even though the URL shows seemingly valid GPG key data.

**Comment by j00bar** [comment] 2017-09-12 17:27
Hi, @jschulthess - Do you mind reporting a separate bug for this, so we can track it on its own and get a complete set of info on how to reproduce? Thanks!

**Comment by jschulthess** [comment] 2017-09-12 18:18
Ok, will do.

**Comment by aric49** [comment] 2017-09-12 22:08
Excellent.  The changes in 0.9.2 seemed to have fixed the issue on my end. Thanks for the quick turn around everyone!

**Comment by amoravek** [comment] 2017-09-13 15:36
0.9.2 fixed my problem too. Thank you
