### ISSUE TITLE
changes in actual role does not rebuild image

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-container#817] opened 2017-12-01 22:56 UTC
##### ISSUE TYPE

 - Bug Report

##### container.yml 

pick any that uses a role 

##### SUMMARY

Build the image, keep the .yml the same, change the role, rebuild (do not use anyof cache busting flags). Notice how the cached image layers are used an no build is done.

##### EXPECTED RESULTS

If role changes, the layer in the image must be rebuild.

##### ACTUAL RESULTS

reusing cache.

Currently using a nasty work around to add a `triggerBuild` var to the role in container.yml with some unused value I change to force the rebuild starting with that layer.

**Comment by chouseknecht** [comment] 2017-12-03 00:07
@hans-d 

Which version of Ansible Container are you using?  On #800 you were using `0.9.2`. A lot has changed since then.

Would be helpful if you could run from the latest source and report back.

Thanks!

**Comment by chouseknecht** [comment] 2017-12-03 19:26
@hans-d 

Closing this, as I can confirm that changing a role by adding an additional task, or making a change to an existing task, does indeed trigger a build. Tested with `0.9.3rc0`, the latest code in the `develop` branch. 

It may very well be broken in `0.9.2`, but I don't think we're planning to update old releases at this point.

If you do find a specific role change in `0.9.3rc0` that does fail to trigger a build, please comment here, and we will re-open.

**Closed as completed by chouseknecht** 2017-12-03 19:26 UTC
