### ISSUE TITLE
Getting started fails 

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible/ansible-container#468] opened 2017-05-01 12:31 UTC
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "2"
settings:
  # The deployment_output_path is mounted to the Conductor container, so
  # that the `run` and `deployment` commands can write generated Ansible
  # playbooks to it.
  # deployment_output_path: ~/ansible-deployment
  # The Conductor container does the heavy lifting, and provides a portable
  # Python runtime for building your target containers. It should be derived
  # from the same distribution as you're building your target containers with.
  conductor_base: centos:7

  # When using the k8s or openshift engines, use the following to authorize with the API.
  # Values set here will be passed to the Ansible modules. Any file paths will be mounted
  # to the conductor container, allowing the `run` command to access the API.
  #k8s_auth:
    # path to a K8s config file
    #config_file:
    # name of a context found within the config.json file
    #context:
    # URL for accessing the K8s API
    #host:
    # An API authentication token
    #api_key:
    # Path to a ca cert file
    #ssl_ca_cert:
    # Path to a cert file
    #cert_file:
    # Path to a key file
    #key_file:
    #boolean, indicating if SSL certs should be validated
    #verify_ssl:

  # When using the k8s or openshift engines, use the following to set the namespace.
  # If not set, the project name will be used. For openshift, the namespace maps to a project,
  # and description and display_name are supported.
  #k8s_namespace:
  #  name:
  #  description:
  #  display_name:

services: {}
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  # web:
  #   from: centos:7
  #   roles:
  #     - apache-container
  #   ports:
  #     - "80:80"
  #   command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   demo:container bas$ 
```

##### main.yml 

```

```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.0.0
Darwin, demo, 16.5.0, Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64, x86_64
2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] /usr/local/opt/python/bin/python2.7
ERROR	The connection to Docker was refused. Check your Docker environment configuration.
```
##### SUMMARY

official Getting Started failes
http://docs.ansible.com/ansible-container/getting_started.html
##### STEPS TO REPRODUCE

```
$ mkdir container
$ cd container/
$ ansible-container init
$ ansible-container build
```

##### EXPECTED RESULTS

ansible-container build initiates the build process. It builds and launches the Conductor Container. The Conductor then runs instances of your base container images as specified in container.yml. The Conductor container applies Ansible roles against them, committing each role as new image layers. Ansible communicates with the other containers through the container engine, not through SSH.
##### ACTUAL RESULTS

```
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 259, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/core.py", line 133, in hostcmd_build
    conductor_container_id = engine_obj.get_container_id_for_service('conductor')
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 347, in get_container_id_for_service
    container_info = self.client.containers.get(self.container_name_for_service(service_name))
AttributeError: 'function' object has no attribute 'get'
```

**Comment by chouseknecht** [comment] 2017-05-01 13:25
@bbaassssiiee 

Thanks for using Ansible Container, and for taking the time to file an issue. 

Agreed, our documentation is in need of an update post 0.9 release. We're working on it.

However, the reason the `build` fails is because your `container.yml` file has no services defined. If you uncomment the example, and add a `roles` directory along with an `apache-container` role, it would work.

I think the *actual* bug here is that it's not failing gracefully, and helping you understand how to fix the issue.

**Comment by j00bar** [comment] 2017-05-02 16:26
@chouseknecht Respectfully disagree. This is a duplicate of #451, I believe.

**Closed** 2017-05-02 16:26 UTC
Labels: duplicate
