### ISSUE TITLE
Error executing ansible-container init

### ISSUE THREAD

**Issue by look4parker** [ansible/ansible-container#439] opened 2017-04-18 21:01 UTC
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ansible-container", line 9, in <module>
    load_entry_point('ansible-container==0.9.0.0', 'console_scripts', 'ansible-container')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/container/cli.py", line 4, in <module>
    from .utils.visibility import getLogger
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/container/utils/__init__.py", line 4, in <module>
    from .visibility import getLogger
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/container/utils/visibility.py", line 14, in <module>
    from ruamel.yaml.compat import ordereddict
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruamel/yaml/__init__.py", line 65, in <module>
    from ruamel.yaml.main import *  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruamel/yaml/main.py", line 17, in <module>
    from ruamel.yaml.dumper import BaseDumper, SafeDumper, Dumper, RoundTripDumper  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruamel/yaml/dumper.py", line 9, in <module>
    from ruamel.yaml.representer import Representer, SafeRepresenter, BaseRepresenter, \
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruamel/yaml/representer.py", line 5, in <module>
    from typing import Dict, List, Any, Union, Text   # NOQA
ImportError: cannot import name 'Text'
```
##### SUMMARY

I cannot execute ansible-container see above output

##### STEPS TO REPRODUCE

I installed ansible-container using:
pip install ansible-container
The install completed successfully but I cannot execute any ansible-container command without error.

```
ansible-container init
ansible-container --debug version
```

##### EXPECTED RESULTS

ansible-container executes as expected without error

##### ACTUAL RESULTS

ansible-container --debug init

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ansible-container", line 9, in <module>
    load_entry_point('ansible-container==0.9.0.0', 'console_scripts', 'ansible-container')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/container/cli.py", line 4, in <module>
    from .utils.visibility import getLogger
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/container/utils/__init__.py", line 4, in <module>
    from .visibility import getLogger
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/container/utils/visibility.py", line 14, in <module>
    from ruamel.yaml.compat import ordereddict
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruamel/yaml/__init__.py", line 65, in <module>
    from ruamel.yaml.main import *  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruamel/yaml/main.py", line 17, in <module>
    from ruamel.yaml.dumper import BaseDumper, SafeDumper, Dumper, RoundTripDumper  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruamel/yaml/dumper.py", line 9, in <module>
    from ruamel.yaml.representer import Representer, SafeRepresenter, BaseRepresenter, \
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruamel/yaml/representer.py", line 5, in <module>
    from typing import Dict, List, Any, Union, Text   # NOQA
ImportError: cannot import name 'Text'
```

**Comment by chouseknecht** [comment] 2017-04-19 18:49
@look4parker 

Thank you for taking the time to open an issue, and share feedback with us. 

You're using `python 3.5`, so  I attempted to duplicate the problem using `pyenv` and a virtualenv. Here's what I tried:

```
$ pyenv virtualenv 3.5.0 actest-3-5-0
$ pyenv activate actest-3-5-0
$ pip install ansible-container

Collecting ansible-container
  Using cached ansible-container-0.9.0.0.tar.gz
Collecting Jinja2>=2.9 (from ansible-container)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from ansible-container)
Collecting requests>=2 (from ansible-container)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting ruamel.yaml>=0.14.2 (from ansible-container)
  Using cached ruamel.yaml-0.14.8.tar.gz
Collecting six>=1.10 (from ansible-container)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting structlog[dev]>=16.1 (from ansible-container)
  Using cached structlog-16.1.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.9->ansible-container)
Collecting colorama (from structlog[dev]>=16.1->ansible-container)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Installing collected packages: MarkupSafe, Jinja2, PyYAML, requests, ruamel.yaml, six, colorama, structlog, ansible-container
  Running setup.py install for ruamel.yaml
  Running setup.py install for ansible-container
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 PyYAML-3.12 ansible-container-0.9.0.0 colorama-0.3.7 requests-2.13.0 ruamel.yaml-0.14.8 six-1.10.0 structlog-16.1.0
```

Then create a project directory, and run `ini`:

```
$ mkdir actest
$ cd actest 
$ ansible-container init

Ansible Container initialized
```
Everything seems to work fine.

**Comment by chouseknecht** [comment] 2017-04-19 18:54
Same is true for Python 2.7:

$ virtualenv actest4
$ source ./actest4/bin/activate
$ pip install ansible-container
Collecting ansible-container
Collecting Jinja2>=2.9 (from ansible-container)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10 in ./actest4/lib/python2.7/site-packages (from ansible-container)
Collecting requests>=2 (from ansible-container)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from ansible-container)
Collecting structlog[dev]>=16.1 (from ansible-container)
  Using cached structlog-16.1.0-py2.py3-none-any.whl
Collecting ruamel.yaml>=0.14.2 (from ansible-container)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.9->ansible-container)
Collecting colorama; extra == "dev" (from structlog[dev]>=16.1->ansible-container)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting ruamel.ordereddict (from ruamel.yaml>=0.14.2->ansible-container)
Collecting typing (from ruamel.yaml>=0.14.2->ansible-container)
Installing collected packages: MarkupSafe, Jinja2, requests, PyYAML, colorama, structlog, ruamel.ordereddict, typing, ruamel.yaml, ansible-container
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 PyYAML-3.12 ansible-container-0.9.0.0 colorama-0.3.7 requests-2.13.0 ruamel.ordereddict-0.4.9 ruamel.yaml-0.14.8 structlog-16.1.0 typing-3.6.1
``` 

Then create a project directory, and run `init`:

```
$ mkdir actest4
$ cd actest4
$ ansible-container init
Ansible Container initialized
```

**Comment by chouseknecht** [comment] 2017-04-19 18:55
Closing. Not able to reproduce.

**Closed** 2017-04-19 18:57 UTC
Labels: bug
